## PREGUNTAS CON EVIDENCIAS.
---
eje1:
  1: false
  2: false
  3: false
  4: false
  5: false
  
eje2:
  1: false
  2: false
  3: false
  4: false
  5: false
  6: false

eje3:
  1: false
  2: false
  3: false
  4: false
  5: false
  6: false

eje4:
  1: false
  2: false
  3: false
  4: false
  5: false
  6: false
  7: false
  
eje5:
  1: false
  2: false
  3: false
  4: false
  5: false
  6: false
