## PREGUNTAS CON EVIDENCIAS.
---
eje1:
  1: true
  2: true
  3: true
  4: true
  5: true
  
eje2:
  1: false
  2: false
  3: false
  4: false
  5: false
  6: true

eje3:
  1: false
  2: false
  3: false
  4: false
  5: false
  6: false

eje4:
  1: false
  2: false
  3: true
  4: true
  5: false
  6: false
  7: false
  
eje5:
  1: true
  2: true
  3: true
  4: true
  5: true
  6: true
